#!/usr/bin/env python3
"""Generate tables/equipment.tex and tables/relics.tex for Beneath The Shard."""

from pathlib import Path

OUT_EQ = Path("/home/msachau/shardbound/tables/equipment.tex")
OUT_REL = Path("/home/msachau/shardbound/tables/relics.tex")


def esc(s: str) -> str:
    return (
        s.replace("&", r"\&")
        .replace("%", r"\%")
        .replace("#", r"\#")
        .replace("_", r"\_")
    )


# --- Equipment catalogs -------------------------------------------------------

WEAPONS = [
    # name, hands, price, effect
    ("Shortsword", "1h", "2", r"Strike: if the die shows a 6, deal $+1$ hit."),
    ("Spear", "1h", "2", r"Strike may target a foe in an adjacent zone."),
    ("Mace", "1h", "2", r"Strike ignores Guard."),
    ("Hand Axe", "1h", "2", r"Strike: if the foe falls, you may Move once for free."),
    ("Dagger", "1h", "1", r"Once per round, if you Moved this phase, you may Strike as \easy (still deals 1 hit)."),
    ("Flail", "1h", "3", r"Strike: ignore Armor on that hit."),
    ("Longsword", "2h", "3", r"Strike deals 2 hits (still \medium{} \energy{1}). Occupies weapon and off-hand."),
    ("Greataxe", "2h", "4", r"You gain the action \textbf{Cleaving Blow} (\hard{} \hard{}): deal 3 hits to one foe in your zone. Occupies weapon and off-hand."),
    ("Warhammer", "2h", "4", r"Strike: deal $+1$ hit and Bind that foe. Occupies weapon and off-hand."),
    ("Bow", "2h", "3", r"Strike may target a foe up to two zones away, but not in your own zone. Occupies weapon and off-hand."),
    ("Crossbow", "2h", "3", r"Strike deals 2 hits to a foe in an adjacent zone; you cannot Move the same round. Occupies weapon and off-hand."),
    ("Shard-Staff", "2h", "4", r"Once per round, raise one die face on a spell you cast by $+1$ (max 6). Occupies weapon and off-hand."),
]

OFFHAND = [
    ("Shield", "2", r"When you Guard, ignore the first \textbf{two} hits, or grant Guard to one ally in your zone instead of yourself."),
    ("Buckler", "1", r"Once per fight, after you take a hit, ignore it (before Armor)."),
    ("Parrying Knife", "1", r"Once per round, when a foe in your zone hits you, deal 1 hit back."),
]

ARMOR = [
    ("None", "0", "0", r"No Armor boxes."),
    ("Light", "1", "2", r"1 Armor box. Soft leather, padded cloak, crystal-scale vest."),
    ("Medium", "2", "4", r"2 Armor boxes. Mail, brigandine, scavenged plate."),
    ("Heavy", "3", "6", r"3 Armor boxes. Full plate or Shard-forged harness. You may \kw{Move} only once per round; Static Field / Static Rain deals 1 hit at round start unless Guarded."),
]

GEAR = [
    ("Rations", "1", "consumable", r"At Camp, spend to regain $+1$ Supply (once per Camp)."),
    ("Bandages", "1", "consumable", r"After a fight, heal 1 Hit on one character (once)."),
    ("Lockpicks", "1", "tool", r"Once per Gate, treat one Hard Hard lock/forge check as Medium."),
    ("Climbing Kit", "1", "tool", r"Once per expedition, ignore one Climb/ford failure on a STR check (still mark the clock/Supply)."),
    ("Lantern", "1", "tool", r"Ignore darkness penalties; Swarm foes prefer the bearer."),
    ("Forged Papers", "2", "consumable", r"Once, auto-succeed one Easy or Medium CHA/INT forgery or passage check; then gone."),
    ("Antidote", "1", "consumable", r"Clear Burning, Bound, or Marked from one character (once)."),
    ("Smoke Pot", "1", "consumable", r"Combat: Easy Use Gear. Until your next round, foes in your zone cannot target adjacent zones."),
    ("Firepot", "1", "consumable", r"Combat: Easy Use Gear. Deal 1 hit to every foe in an adjacent zone; they are Burning."),
    ("Flash Glass", "1", "consumable", r"Combat: Easy Use Gear. One foe in your zone loses Guard and is Marked."),
    ("Crowbar", "1", "tool", r"$+1$ die on one STR force/pry check per Gate."),
    ("Rope and Grapple", "1", "tool", r"Once per Gate, treat a Vertical Drop Move as a single zone."),
    ("Spare Kit", "1", "tool", r"Once per expedition, restore 1 spent Armor box outside combat."),
    ("Guild Token", "2", "token", r"Spend to clear 1 Guild Debt pressure, or as 1 Favor for a Guild Bargain."),
    ("Cult Charm", "1", "token", r"Once per Gate, reroll one Omen result; keep the second."),
    ("Field Journal", "1", "tool", r"Once per Camp, Scout or Lore Counsel without counting as one of your two Counsel picks."),
]


def emit_equipment():
    lines = [
        r"% Auto-generated by scripts/generate_equipment.py --- do not edit by hand.",
        "",
        r"\subsubsection{Weapons}",
        "",
    ]
    wrows = []
    for i, (n, h, p, e) in enumerate(WEAPONS):
        color = r"\rowcolor{bone}" if i % 2 == 0 else r"\rowcolor{ash!15}"
        wrows.append(f"  {color} {esc(n)} & {h} & {p} & {e} \\\\")
    lines.append(r"{\small")
    lines.append(r"\renewcommand{\arraystretch}{1.15}")
    lines.append(
        r"\begin{tabularx}{\linewidth}{>{\raggedright\arraybackslash}p{2.4cm} c c >{\raggedright\arraybackslash}X}"
    )
    lines.append(
        r"  \shardheadercell{Weapon} & \shardheadercell{Hands} & \shardheadercell{Price} & \shardheadercell{Effect} \\"
    )
    lines.extend(wrows)
    lines.append(r"\end{tabularx}")
    lines.append(r"}")
    lines.append("")
    lines.append(r"Price is in \textbf{Refined} crystals. Two-handed weapons fill the weapon and off-hand slots.")
    lines.append("")

    lines.append(r"\subsubsection{Off-Hand}")
    lines.append("")
    lines.append(r"{\small")
    lines.append(r"\renewcommand{\arraystretch}{1.15}")
    lines.append(
        r"\begin{tabularx}{\linewidth}{>{\raggedright\arraybackslash}p{2.6cm} c >{\raggedright\arraybackslash}X}"
    )
    lines.append(
        r"  \shardheadercell{Item} & \shardheadercell{Price} & \shardheadercell{Effect} \\"
    )
    for i, (n, p, e) in enumerate(OFFHAND):
        color = r"\rowcolor{bone}" if i % 2 == 0 else r"\rowcolor{ash!15}"
        lines.append(f"  {color} {esc(n)} & {p} & {e} \\\\")
    lines.append(r"\end{tabularx}")
    lines.append(r"}")
    lines.append("")

    lines.append(r"\subsubsection{Armor}")
    lines.append("")
    lines.append(r"{\small")
    lines.append(r"\renewcommand{\arraystretch}{1.15}")
    lines.append(
        r"\begin{tabularx}{\linewidth}{>{\raggedright\arraybackslash}p{1.8cm} c c >{\raggedright\arraybackslash}X}"
    )
    lines.append(
        r"  \shardheadercell{Armor} & \shardheadercell{Boxes} & \shardheadercell{Price} & \shardheadercell{Notes} \\"
    )
    for i, (n, b, p, e) in enumerate(ARMOR):
        color = r"\rowcolor{bone}" if i % 2 == 0 else r"\rowcolor{ash!15}"
        lines.append(f"  {color} {esc(n)} & {b} & {p} & {e} \\\\")
    lines.append(r"\end{tabularx}")
    lines.append(r"}")
    lines.append("")

    lines.append(r"\subsubsection{Gear and Consumables}")
    lines.append("")
    lines.append(r"{\small")
    lines.append(r"\renewcommand{\arraystretch}{1.15}")
    lines.append(
        r"\begin{tabularx}{\linewidth}{>{\raggedright\arraybackslash}p{2.6cm} c c >{\raggedright\arraybackslash}X}"
    )
    lines.append(
        r"  \shardheadercell{Item} & \shardheadercell{Price} & \shardheadercell{Type} & \shardheadercell{Effect} \\"
    )
    for i, (n, p, t, e) in enumerate(GEAR):
        color = r"\rowcolor{bone}" if i % 2 == 0 else r"\rowcolor{ash!15}"
        lines.append(f"  {color} {esc(n)} & {p} & {esc(t)} & {e} \\\\")
    lines.append(r"\end{tabularx}")
    lines.append(r"}")
    lines.append("")
    lines.append(
        r"Consumables are gone when spent. Tools stay until the text says otherwise. Use Gear is an Easy Basic Action in combat."
    )
    lines.append("")

    OUT_EQ.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT_EQ}")


# --- Relics -------------------------------------------------------------------

COMMON = [
    ("Ash Cloak", r"Once per fight, ignore the first hit from a Rear foe."),
    ("Iron Nail Charm", r"Your first Strike each fight deals $+1$ hit."),
    ("Bone Dice", r"Once per Camp, reroll one Attribute Check die."),
    ("Guild Brass Ring", r"Bargain with the Guild at $+1$ face once per Town."),
    ("Vein Whisper", r"Once per Gate, learn if an adjacent hex holds a Gate (yes/no)."),
    ("Cracked Lens", r"Once per fight, raise one assigned die face by $+1$ (max 6)."),
    ("Salt Band", r"Ignore the first plague Hazard hit each expedition."),
    ("Lantern Shard", r"Lantern effect without occupying a gear slot; Swarm still prefer you."),
    ("Soft Boots", r"Once per Gate, treat one Easy DEX sneak as automatic success."),
    ("Scar Salve Tin", r"Once per campaign, ignore one Scar you would take."),
    ("Crow Feather", r"Once per fight, Move as a free Easy (no die)."),
    ("Debt Stub", r"Spend to clear 1 Debt with any faction (then destroy)."),
    ("Glass Bead", r"Reclaim 1 Energy when you first enter a Gate each expedition."),
    ("Pit Badge", r"Hold the Line / Guard allies: Guard lasts until end of next round once per fight."),
    ("Tunnel Chalk", r"Once per delve, mark a chamber as explored without rolling Feature next visit to that hex."),
    ("Rust Key", r"Once per Gate, open one locked Vault Door as Medium instead of Hard Hard."),
    ("Ember Thumb Ring", r"Your first hit each fight also sets the foe Burning."),
    ("Quiet Bell", r"Once per fight, cancel one Swarm Move into your zone."),
    ("Marching Strap", r"Once per expedition, ignore one Supply cost for a Camp."),
    ("Whetstone of Dust", r"Once per fight, Strike ignores Guard."),
]

UNCOMMON = [
    ("Mirror Shard", r"\defensive{} Once per fight, redirect the first hit you would take to a foe in your zone."),
    ("Resonance Ear", r"Once per Gate, roll Omen twice and pick one."),
    ("Blood Ledger Clip", r"When you drop a foe, reclaim 1 Energy (once per fight)."),
    ("Ashsteel Torc", r"Gain $+1$ Armor box while bound (stacks with worn armor for absorption order after Guard)."),
    ("Gatecutter's Pick", r"Once per delve, auto-succeed one Medium DEX lock/scout check."),
    ("Cantor's Reed", r"Once per fight, one ally in your zone gains Guard."),
    ("Void Thread", r"Once per fight, Bind one foe in your zone (no die; after a successful Strike)."),
    ("Crown Bailiff Seal", r"Clear 1 Crown Debt when you Camp on Crown Scar Road (once per expedition)."),
    ("Star-Cult Rosary", r"Spend Cult Favor once per Gate to ignore $+1$ Stress from a single source."),
    ("Hound Tooth", r"Strike against the most wounded foe in reach deals $+1$ hit."),
    ("Glass Lung Filter", r"Ignore Exhausted's $-1$ die once per expedition."),
    ("Phalanx Brooch", r"\defensive{} Allies in your zone ignore the first hit each fight."),
    ("Smuggler's Purse", r"Carry $+1$ Raw without the usual Stress for carrying it out of one Gate."),
    ("Echo Needle", r"Once per fight, Mark a foe in any zone."),
    ("Aetherwick", r"Once per Camp, burn to refill 2 Energy without a full Camp Energy refill counting this as Counsel."),
]

RARE = [
    ("Captain's Gorget", r"\defensive{} Guard ignores three hits. Bind cost: mutation check."),
    ("Veinheart Spike", r"Strike deals $+1$ hit always. Once per fight, ignore Armor."),
    ("Night Broker Contract", r"Once per delve, force one Minion to skip its phase."),
    ("Seer's Prism", r"Once per fight, discard and redraw up to two unassigned party dice."),
    ("Iron Oath Plate", r"\defensive{} Restore 1 Armor box at the start of each fight."),
    ("Hungering Knife", r"When you deal 3+ hits with one action, heal 1 Hit (once per fight)."),
    ("Static Null Rod", r"Ignore Static Field / Static Rain hits. Heavy armor Move limit still applies."),
    ("Choir Mask", r"Once per fight, deal 1 hit to every foe in your zone (\medium{} \energy{1} action added while bound)."),
    ("Deep Gate Key", r"Once per campaign, enter one ring-B Gate without rolling Omen (still Camp first)."),
    ("Ash Phoenix Band", r"Once per campaign, when you would go Down, stand with 2 Hits and take no Scar."),
]

PRISMATIC = [
    ("Heart-Splinter Crown", r"Pool $+1$ die while bound (max 5). Mark $+1$ Stress each Gate entry."),
    ("World-Crack Lens", r"Once per fight, cast one Circle II spell you know without Energy (Stress still applies if printed)."),
    ("Nameless Blade", r"Strike deals 2 hits and ignores Guard and Armor. Each fight you use it, mark $+1$ Stress."),
    ("Star-Grave Mantle", r"\defensive{} Ignore all hits from one Monster phase per fight. Then mark $+1$ Stress."),
    ("Cabal's Last Pattern", r"Once per campaign, treat one Fell action as Dire for dice needed (still pay Fell Energy). Mark $+2$ Stress."),
]


def relic_table(title, items, rollup=None):
    """items: list of (name, effect). If len < 20, pad with rollup instruction rows."""
    lines = [rf"\paragraph{{{title}.}}", ""]
    lines.append(r"{\small")
    lines.append(r"\renewcommand{\arraystretch}{1.12}")
    lines.append(
        r"\begin{tabularx}{\linewidth}{c >{\raggedright\arraybackslash}p{3.0cm} >{\raggedright\arraybackslash}X}"
    )
    lines.append(
        r"  \shardheadercell{d20} & \shardheadercell{Relic} & \shardheadercell{Effect} \\"
    )
    n = len(items)
    for i, (name, effect) in enumerate(items, start=1):
        color = r"\rowcolor{bone}" if i % 2 == 1 else r"\rowcolor{ash!15}"
        lines.append(f"  {color} {i} & {esc(name)} & {effect} \\\\")
    if rollup and n < 20:
        # Fill remaining with roll-up bands
        start = n + 1
        # Map remaining slots to higher tables
        remaining = list(range(start, 21))
        # Simple: last few say roll next table
        for j, d in enumerate(remaining):
            color = r"\rowcolor{bone}" if d % 2 == 1 else r"\rowcolor{ash!15}"
            lines.append(f"  {color} {d} & --- & {rollup} \\\\")
    lines.append(r"\end{tabularx}")
    lines.append(r"}")
    lines.append("")
    return lines


def emit_relics():
    lines = [
        r"% Auto-generated by scripts/generate_equipment.py --- do not edit by hand.",
        "",
    ]
    # Common: exactly 20
    assert len(COMMON) == 20
    lines.extend(relic_table("Common (rings E--D)", COMMON))
    # Uncommon: 15 + rollup 16-20
    assert len(UNCOMMON) == 15
    lines.extend(
        relic_table(
            "Uncommon (ring C)",
            UNCOMMON,
            rollup=r"Roll on the Rare table instead.",
        )
    )
    # Rare: 10 + rollup
    assert len(RARE) == 10
    lines.extend(
        relic_table(
            "Rare (ring B)",
            RARE,
            rollup=r"Roll on the Prismatic table (1--5) or Rare again (6--20 on a second d20).",
        )
    )
    # Prismatic: 5 entries, use d10/2 or d5 — plan says d20 tables; use 1-5 and 6-20 reroll
    assert len(PRISMATIC) == 5
    lines.append(r"\paragraph{Prismatic (Star-Grave / Prismatic crystal).}")
    lines.append("")
    lines.append(r"Roll \D{1}{5}, or \D{1}{20} and use $((result-1) \bmod 5)+1$.")
    lines.append("")
    lines.append(r"{\small")
    lines.append(r"\renewcommand{\arraystretch}{1.12}")
    lines.append(
        r"\begin{tabularx}{\linewidth}{c >{\raggedright\arraybackslash}p{3.2cm} >{\raggedright\arraybackslash}X}"
    )
    lines.append(
        r"  \shardheadercell{d5} & \shardheadercell{Relic} & \shardheadercell{Effect} \\"
    )
    for i, (name, effect) in enumerate(PRISMATIC, start=1):
        color = r"\rowcolor{bone}" if i % 2 == 1 else r"\rowcolor{ash!15}"
        lines.append(f"  {color} {i} & {esc(name)} & {effect} \\\\")
    lines.append(r"\end{tabularx}")
    lines.append(r"}")
    lines.append("")

    OUT_REL.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT_REL}")


def main():
    emit_equipment()
    emit_relics()


if __name__ == "__main__":
    main()
